services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kokoc
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_LOGGING: DEBUG
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d kokoc" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic init -t async migration; alembic revision --autogenerate -m "Initial revision"; alembic stamp head; alembic revision --autogenerate -m "Initial revision"; alembic upgrade head; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8080:8000
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: kokoc
      ACCESS_SECRET_KEY: 1d9a7b4577355c1e0c8d31edf503ef4d85e4b3f9f1c96506dde4ebc4a68d2885
      REFRESH_SECRET_KEY: 1d9a7b4577355c1e0c8d31edf503ef4d85e4b3f9f1c96506dde4ebc4a68d2885
    depends_on:
      db:
        condition: service_healthy
volumes:
  pgdata:
    driver: local