services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kokoc
      POSTGRES_LOGGING: DEBUG
    ports:
      - 5434:5432
    volumes:
      - ./kokoc_db.backup:/backup/kokoc_db.backup
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d kokoc" ]
      interval: 10s
      timeout: 30s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8080:8000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: kokoc
      ACCESS_SECRET_KEY: 1d9a7b4577355c1e0c8d31edf503ef4d85e4b3f9f1c96506dde4ebc4a68d2885
      REFRESH_SECRET_KEY: 1d9a7b4577355c1e0c8d31edf503ef4d85e4b3f9f1c96506dde4ebc4a68d2885
      IMAGES_PATH: /app/images/
    depends_on:
      db:
        condition: service_healthy