"""Initial revision

Revision ID: 02d414567562
Revises: dc5a37da8ccc
Create Date: 2024-10-07 20:46:27.288433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d414567562'
down_revision: Union[str, None] = 'dc5a37da8ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'id')
    op.add_column('roles_permissions', sa.Column('permission', sa.String(length=256), nullable=False))
    op.drop_constraint('roles_permissions_permission_id_fkey', 'roles_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'roles_permissions', 'permissions', ['permission'], ['name'])
    op.drop_column('roles_permissions', 'permission_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles_permissions', sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles_permissions', type_='foreignkey')
    op.create_foreign_key('roles_permissions_permission_id_fkey', 'roles_permissions', 'permissions', ['permission_id'], ['id'])
    op.drop_column('roles_permissions', 'permission')
    op.add_column('permissions', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('permissions_id_seq'::regclass)"), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
