"""Initial revision

Revision ID: 09270c9f787c
Revises: ae87310d503c
Create Date: 2024-10-10 18:24:25.820172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09270c9f787c'
down_revision: Union[str, None] = 'ae87310d503c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_content_gin', 'news', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_gin', table_name='news', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    # ### end Alembic commands ###
