"""Initial revision

Revision ID: 0a6c4c7a522a
Revises: 48fe461bb873
Create Date: 2024-10-08 12:24:57.680201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6c4c7a522a'
down_revision: Union[str, None] = '48fe461bb873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('category_name', sa.String(), nullable=False))
    op.drop_column('news', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('news', 'category_name')
    # ### end Alembic commands ###
