"""Initial revision

Revision ID: 1bf23833b460
Revises: aef7853f44f8
Create Date: 2024-10-08 12:42:18.845334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf23833b460'
down_revision: Union[str, None] = 'aef7853f44f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'news', 'news_categories', ['category_name'], ['name'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    # ### end Alembic commands ###
