"""Initial revision

Revision ID: 1c7d6edbdba2
Revises: 09270c9f787c
Create Date: 2024-10-10 18:49:09.340635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c7d6edbdba2'
down_revision: Union[str, None] = '09270c9f787c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_gin', table_name='news', postgresql_using='gin')
    op.create_index('ix_title_content', 'news', [sa.text("(to_tsvector(text('russian'), 'title') + to_tsvector(text('russian'), 'content'))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_title_content', table_name='news', postgresql_using='gin')
    op.create_index('ix_content_gin', 'news', ['content'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
