"""Initial revision

Revision ID: 3250ca6ca7d1
Revises: 9fbcc6c5810c
Create Date: 2024-10-06 09:59:06.521295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3250ca6ca7d1'
down_revision: Union[str, None] = '9fbcc6c5810c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refresh_tokens_token_key', 'refresh_tokens', type_='unique')
    op.drop_column('refresh_tokens', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint('refresh_tokens_token_key', 'refresh_tokens', ['token'])
    # ### end Alembic commands ###
