"""Initial revision

Revision ID: 46b3c0f6041d
Revises: 9f3cf7fe6edc
Create Date: 2024-10-06 18:06:53.974407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b3c0f6041d'
down_revision: Union[str, None] = '9f3cf7fe6edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
