"""Initial revision

Revision ID: 48fe461bb873
Revises: decd153c6ecd
Create Date: 2024-10-08 12:24:17.064187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48fe461bb873'
down_revision: Union[str, None] = 'decd153c6ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('category_name', sa.String(), nullable=False))
    op.drop_column('news', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('news', 'category_name')
    # ### end Alembic commands ###
