"""Initial revision

Revision ID: 5675585af5bc
Revises: 78f6a6fcb4fb
Create Date: 2024-10-09 21:02:00.328090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5675585af5bc'
down_revision: Union[str, None] = '78f6a6fcb4fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'status')
    # ### end Alembic commands ###
