"""Initial revision

Revision ID: 5a672768d26d
Revises: 9a25053ab495
Create Date: 2024-10-09 19:44:00.280804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a672768d26d'
down_revision: Union[str, None] = '9a25053ab495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('height', sa.Integer(), nullable=True))
    op.drop_column('team_members', 'heigth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('heigth', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('team_members', 'height')
    # ### end Alembic commands ###
