"""Initial revision

Revision ID: 5b82a1cc1edf
Revises: 9e477c55aa34
Create Date: 2024-10-12 11:05:42.170813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b82a1cc1edf'
down_revision: Union[str, None] = '9e477c55aa34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sizes',
    sa.Column('size', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('size')
    )
    op.create_table('store_categories',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('store_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category_name', sa.String(length=64), nullable=False),
    sa.Column('male', sa.String(length=8), nullable=False),
    sa.Column('image_url', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_name'], ['store_categories.name'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_items_sizes',
    sa.Column('store_item_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['size'], ['sizes.size'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_item_id'], ['store_items.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('store_item_id', 'size')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_items_sizes')
    op.drop_table('store_items')
    op.drop_table('store_categories')
    op.drop_table('sizes')
    # ### end Alembic commands ###
