"""Initial revision

Revision ID: 64292c7d504b
Revises: 58c63da747ff
Create Date: 2024-10-08 00:30:35.845868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64292c7d504b'
down_revision: Union[str, None] = '58c63da747ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'access_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('access_level', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
