"""Initial revision

Revision ID: 721392df3ae9
Revises: e8be4f624b47
Create Date: 2024-10-11 13:28:04.894694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721392df3ae9'
down_revision: Union[str, None] = 'e8be4f624b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('first_team_score', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('events', 'fisrt_team_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('fisrt_team_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('events', 'first_team_score')
    # ### end Alembic commands ###
