"""Initial revision

Revision ID: 787d6548dcbd
Revises: 5a672768d26d
Create Date: 2024-10-09 20:53:36.268990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '787d6548dcbd'
down_revision: Union[str, None] = '5a672768d26d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('news_actions_news_id_fkey', 'news_actions', type_='foreignkey')
    op.alter_column('team_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('news_actions_news_id_fkey', 'news_actions', 'news', ['news_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###
