"""Initial revision

Revision ID: 78f6a6fcb4fb
Revises: 787d6548dcbd
Create Date: 2024-10-09 20:55:20.653704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f6a6fcb4fb'
down_revision: Union[str, None] = '787d6548dcbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('news_actions_user_id_fkey', 'news_actions', type_='foreignkey')
    op.create_foreign_key(None, 'news_actions', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'news_actions', 'news', ['news_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_actions', type_='foreignkey')
    op.drop_constraint(None, 'news_actions', type_='foreignkey')
    op.create_foreign_key('news_actions_user_id_fkey', 'news_actions', 'users', ['user_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###
