"""Initial revision

Revision ID: 829bcd027212
Revises: 8e9c6cec6f20
Create Date: 2024-10-10 19:04:53.388985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '829bcd027212'
down_revision: Union[str, None] = '8e9c6cec6f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_gin', table_name='news', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_content_gin', 'news', ['content'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
