"""Initial revision

Revision ID: 8af0bd3554ba
Revises: 1b4424533001
Create Date: 2024-10-12 22:09:49.592166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af0bd3554ba'
down_revision: Union[str, None] = '1b4424533001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_items', 'male')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_items', sa.Column('male', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
