"""Initial revision

Revision ID: 9c5cc5601315
Revises: 70fe282bc4ec
Create Date: 2024-10-09 21:04:14.771532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5cc5601315'
down_revision: Union[str, None] = '70fe282bc4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('status', sa.String(), server_default='available', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'status')
    # ### end Alembic commands ###
