"""Initial revision

Revision ID: 9e476255c0b0
Revises: a0a291cccbe8
Create Date: 2024-10-10 19:03:00.634331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e476255c0b0'
down_revision: Union[str, None] = 'a0a291cccbe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_gin', table_name='news', postgresql_using='gin')
    op.create_index('ix_title_content', 'news', [sa.text("(coalesce('title', '') || coalesce('content', ''))")], unique=False, postgresql_using='gin', postgresql_ops={'news_search': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_title_content', table_name='news', postgresql_using='gin', postgresql_ops={'news_search': 'gin_trgm_ops'})
    op.create_index('ix_content_gin', 'news', ['content'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
