"""Initial revision

Revision ID: a4b162fab8ae
Revises: f93842a0276a
Create Date: 2024-10-10 18:56:07.177027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b162fab8ae'
down_revision: Union[str, None] = 'f93842a0276a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_gin', table_name='news', postgresql_using='gin')
    op.create_index('ix_title_content', 'news', [sa.text("(coalesce(title, '') || coalesce(content, ''))")], unique=False, postgresql_using='gin', postgresql_ops={'columns': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_title_content', table_name='news', postgresql_using='gin', postgresql_ops={'columns': 'gin_trgm_ops'})
    op.create_index('ix_content_gin', 'news', ['content'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
