"""Initial revision

Revision ID: a54a50604ea6
Revises: 829bcd027212
Create Date: 2024-10-10 19:15:05.960737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54a50604ea6'
down_revision: Union[str, None] = '829bcd027212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_title_content', table_name='news', postgresql_using='gin')
    op.create_index('ix_title_content', 'news', [sa.text("(coalesce(title, '') || coalesce(extract_text_from_json(content), ''))")], unique=False, postgresql_using='gin', postgresql_ops={'news_search': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_title_content', table_name='news', postgresql_using='gin', postgresql_ops={'news_search': 'gin_trgm_ops'})
    op.create_index('ix_title_content', 'news', [sa.text("(COALESCE(title, ''::character varying)::text || COALESCE(content, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
