"""Initial revision

Revision ID: a8786dac2d2b
Revises: 0a6c4c7a522a
Create Date: 2024-10-08 12:25:33.557040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8786dac2d2b'
down_revision: Union[str, None] = '0a6c4c7a522a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('category_name', sa.String(), server_default='cat', nullable=False))
    op.drop_column('news', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('news', 'category_name')
    # ### end Alembic commands ###
