"""Initial revision

Revision ID: b2cd6470f785
Revises: 633c746e276b
Create Date: 2024-10-06 16:17:38.680033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2cd6470f785'
down_revision: Union[str, None] = '633c746e276b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_id_key', 'roles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('roles_id_key', 'roles', ['id'])
    # ### end Alembic commands ###
