"""Initial revision

Revision ID: d38d2b808f72
Revises: 3aed22813a22
Create Date: 2024-10-08 12:37:43.579932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd38d2b808f72'
down_revision: Union[str, None] = '3aed22813a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_categories',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_constraint('news_actions_news_id_fkey', 'news_actions', type_='foreignkey')
    op.create_foreign_key(None, 'news_actions', 'news', ['news_id'], ['id'], onupdate='CASCADE', ondelete='NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_actions', type_='foreignkey')
    op.create_foreign_key('news_actions_news_id_fkey', 'news_actions', 'news', ['news_id'], ['id'])
    op.drop_table('news_categories')
    # ### end Alembic commands ###
