"""Initial revision

Revision ID: decd153c6ecd
Revises: b6d2742ea951
Create Date: 2024-10-08 12:23:26.147787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'decd153c6ecd'
down_revision: Union[str, None] = 'b6d2742ea951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('category_name', sa.String(), nullable=False))
    op.drop_column('news', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('news', 'category_name')
    # ### end Alembic commands ###
