"""Initial revision

Revision ID: edef30a901e3
Revises: 5bf33af75227
Create Date: 2024-10-11 12:05:14.517822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edef30a901e3'
down_revision: Union[str, None] = '5bf33af75227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_title_content', table_name='news', postgresql_using='gin')
    op.create_index('ix_title_content', 'news', [sa.text("to_tsvector(regconfig('russian'), coalesce(title, '') || coalesce(content, ''))")], unique=False, postgresql_using='rum', postgresql_ops={'news_search': 'rum_tsvector_ops'})
    op.alter_column('team_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_title_content', table_name='news', postgresql_using='rum', postgresql_ops={'news_search': 'rum_tsvector_ops'})
    op.create_index('ix_title_content', 'news', [sa.text("(COALESCE(title, ''::character varying)::text || COALESCE(content, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
