"""Initial revision

Revision ID: f93842a0276a
Revises: 1c7d6edbdba2
Create Date: 2024-10-10 18:51:10.018157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93842a0276a'
down_revision: Union[str, None] = '1c7d6edbdba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_gin', table_name='news', postgresql_using='gin')
    op.create_index('ix_title_content', 'news', [sa.text("(to_tsvector(text('russian'), title) + to_tsvector(text('russian'), content))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_title_content', table_name='news', postgresql_using='gin')
    op.create_index('ix_content_gin', 'news', ['content'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
